// Centralized status constants to avoid drift across routes
export const STATUS = {
  AGUARDANDO_APROVACAO: 'AGUARDANDO APROVAÇÃO DA COLETA',
  SOLICITACAO_MUDANCA_DATA: 'SOLICITAÇÃO DE MUDANÇA DE DATA',
  APROVACAO_NOVA_DATA: 'APROVAÇÃO NOVA DATA',
  AGUARDANDO_COLETA: 'AGUARDANDO COLETA',
  PONTO_COLETA_SELECIONADO: 'PONTO DE COLETA SELECIONADO',
  APPROVED: 'approved',
  REQUESTED: 'requested',
  FASE_ORCAMENTARIA: 'FASE ORÇAMENTÁRIA',
  ORCAMENTO_PENDENTE: 'ORÇAMENTO PENDENTE',
  ORCAMENTO_APROVADO: 'ORÇAMENTO APROVADO',
  ORCAMENTO_REJEITADO: 'ORÇAMENTO REJEITADO',
  SERVICO_EM_ANDAMENTO: 'SERVIÇO EM ANDAMENTO',
  SERVICO_CONCLUIDO: 'SERVIÇO CONCLUÍDO',
} as const;

export type StatusValue = (typeof STATUS)[keyof typeof STATUS];
