export const VehicleStatus = {
  AGUARDANDO_COLETA: 'AGUARDANDO COLETA',
  AGUARDANDO_CHEGADA: 'AGUARDANDO CHEGADA DO VEÍCULO',
  CHEGADA_CONFIRMADA: 'CHEGADA CONFIRMADA',
  EM_ANALISE: 'EM ANÁLISE',
  FASE_ORCAMENTARIA: 'FASE ORÇAMENTÁRIA',
  ANALISE_FINALIZADA: 'ANALISE FINALIZADA',
  ORCAMENTO_APROVADO: 'Orçamento Aprovado',
  FASE_EXECUCAO_INICIADA: 'FASE DE EXECUÇÃO INICIADA',
} as const;

export type VehicleStatus = (typeof VehicleStatus)[keyof typeof VehicleStatus];
